### ISSUE TITLE
Re-using of IP address of terminated PODS

### ISSUE THREAD

**Issue by subrnath** [Intel-Corp/multus-cni#54] opened 2018-04-13 07:44 UTC
There is an issue raised for the IPv6 - https://github.com/Intel-Corp/multus-cni/issues/48. This issue is with IPV4. if the POD is terminated, IP address of the terminated POD doesn't get re-allocated to a new POD, deployed with a different docker image than the terminated POD. If the new POD is deployed with the same Docker image, IP address of the terminated POD is re-allocated. 

Workaround of the problem - once the POD is terminated, delete the /var/lib/cni/networks/<network id>.

**Comment by s1061123** [comment] 2018-04-23 05:43
Hi @subrnath 

Regarding above comment, you may use 'host-local' plugin for IP Address Management (IPAM) and the issue is related to 'host-local' plugin, not multus-cni.
https://github.com/containernetworking/plugins/tree/master/plugins/ipam/host-local

So I guess it might be wrong place to discuss about it.
Could you please double check about it?

**Comment by subrnath** [comment] 2018-04-23 20:13
Thanks. yes, we are using host-local. I will raise the question on host-local.

**Comment by s1061123** [comment] 2018-04-24 03:13
@subrnath Thanks. I close this issue.

**Closed by s1061123** 2018-04-24 03:13 UTC
